import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { CartProvider } from "@/contexts/CartContext";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <CartProvider>
          <NavBar />
          {children}
        </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
